spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging.level:
  org.hibernate.SQL: